print("How old are you ?",end=" ")
age=input()
print("How tell are you?",end=" ")
height=input()
print("How much do you weight?",end=" ")
weight=input()
print(f"So,you're {age} old,{weight} tall and {weight} heavy.")